### ISSUE TITLE
Make hook_menu items a page so webmaster can add content

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/facilities.uiowa.edu#69]
## Todo
- [x] Enable blocks in paragraphs blocks.

## Basic pages to re-create
- [x] $items['buildings'] - Building Information
- [x] $items['building-coordinators'] - Building Coordinators
- [x] $items['staff-directory'] - Staff Directory
- [x] $items['art-on-campus/map'] - Art on Campus Map
